#!/bin/sh
# MIT License
#
# Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# configure.sh - Dependency detection for rocm-examples Makefile build system
#
# Probes for external dependencies and writes a config.mk file that individual
# example Makefiles include to decide whether to build or skip.
#
# Usage:
#   ./configure.sh [--rocm-path=DIR]
#
# Output:
#   config.mk in the repository root

set -e

ROCM_PATH="/opt/rocm"

for arg in "$@"; do
    case "$arg" in
        --rocm-path=*)
            ROCM_PATH="${arg#--rocm-path=}"
            ;;
        --help|-h)
            echo "Usage: $0 [--rocm-path=DIR]"
            echo "  --rocm-path=DIR  Path to ROCm installation (default: /opt/rocm)"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg" >&2
            exit 1
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_MK="${SCRIPT_DIR}/config.mk"

echo "configure: detecting dependencies (ROCm path: ${ROCM_PATH})"

# Helper: check via pkg-config
pkg_check() {
    pkg-config --exists "$@" 2>/dev/null
}

# Helper: get pkg-config cflags
pkg_cflags() {
    pkg-config --cflags "$@" 2>/dev/null || true
}

# Helper: get pkg-config libs
pkg_libs() {
    pkg-config --libs "$@" 2>/dev/null || true
}

# Helper: verify that libraries from pkg-config can actually be linked.
# On some distros (e.g. SLES), .pc files exist but -dev packages are missing.
# Uses the C compiler to do a link test.
can_link() {
    _libs="$(pkg_libs "$@")"
    if [ -z "$_libs" ]; then
        return 1
    fi
    _cc="${CC:-cc}"
    echo "int main(){return 0;}" | "$_cc" -x c - $_libs -o /dev/null 2>/dev/null
}

# Start writing config.mk
cat > "${CONFIG_MK}" << 'HEADER'
# Auto-generated by configure.sh - do not edit
# Re-run ./configure.sh to regenerate
HEADER

echo "" >> "${CONFIG_MK}"

# --- FFmpeg (libavcodec, libavformat, libavutil) ---
HAVE_FFMPEG=0
FFMPEG_CFLAGS=""
FFMPEG_LIBS=""
if pkg_check libavcodec libavformat libavutil && can_link libavcodec libavformat libavutil; then
    HAVE_FFMPEG=1
    FFMPEG_CFLAGS="$(pkg_cflags libavcodec libavformat libavutil)"
    FFMPEG_LIBS="$(pkg_libs libavcodec libavformat libavutil)"
fi
echo "  FFmpeg: $([ ${HAVE_FFMPEG} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_FFMPEG := ${HAVE_FFMPEG}
FFMPEG_CFLAGS := ${FFMPEG_CFLAGS}
FFMPEG_LIBS := ${FFMPEG_LIBS}
EOF

# --- OpenCV ---
HAVE_OPENCV=0
OPENCV_CFLAGS=""
OPENCV_LIBS=""
if pkg_check opencv4 && can_link opencv4; then
    HAVE_OPENCV=1
    OPENCV_CFLAGS="$(pkg_cflags opencv4)"
    OPENCV_LIBS="$(pkg_libs opencv4)"
elif pkg_check opencv && can_link opencv; then
    HAVE_OPENCV=1
    OPENCV_CFLAGS="$(pkg_cflags opencv)"
    OPENCV_LIBS="$(pkg_libs opencv)"
fi
echo "  OpenCV: $([ ${HAVE_OPENCV} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_OPENCV := ${HAVE_OPENCV}
OPENCV_CFLAGS := ${OPENCV_CFLAGS}
OPENCV_LIBS := ${OPENCV_LIBS}
EOF

# --- GLFW3 ---
HAVE_GLFW3=0
GLFW3_CFLAGS=""
GLFW3_LIBS=""
if pkg_check glfw3 && can_link glfw3; then
    HAVE_GLFW3=1
    GLFW3_CFLAGS="$(pkg_cflags glfw3)"
    GLFW3_LIBS="$(pkg_libs glfw3)"
fi
echo "  GLFW3: $([ ${HAVE_GLFW3} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_GLFW3 := ${HAVE_GLFW3}
GLFW3_CFLAGS := ${GLFW3_CFLAGS}
GLFW3_LIBS := ${GLFW3_LIBS}
EOF

# --- Vulkan ---
HAVE_VULKAN=0
VULKAN_CFLAGS=""
VULKAN_LIBS=""
if pkg_check vulkan && can_link vulkan; then
    HAVE_VULKAN=1
    VULKAN_CFLAGS="$(pkg_cflags vulkan)"
    VULKAN_LIBS="$(pkg_libs vulkan)"
fi
echo "  Vulkan: $([ ${HAVE_VULKAN} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_VULKAN := ${HAVE_VULKAN}
VULKAN_CFLAGS := ${VULKAN_CFLAGS}
VULKAN_LIBS := ${VULKAN_LIBS}
EOF

# --- libdw (elfutils) ---
HAVE_LIBDW=0
if pkg_check libdw; then
    HAVE_LIBDW=1
elif [ -f /usr/include/elfutils/libdw.h ] || [ -f /usr/include/dwarf.h ]; then
    HAVE_LIBDW=1
fi
echo "  libdw: $([ ${HAVE_LIBDW} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_LIBDW := ${HAVE_LIBDW}
EOF

# --- amd_comgr ---
HAVE_AMD_COMGR=0
if [ -f "${ROCM_PATH}/include/amd_comgr/amd_comgr.h" ] || [ -f "${ROCM_PATH}/lib/libamd_comgr.so" ]; then
    HAVE_AMD_COMGR=1
elif pkg_check amd_comgr; then
    HAVE_AMD_COMGR=1
fi
echo "  amd_comgr: $([ ${HAVE_AMD_COMGR} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_AMD_COMGR := ${HAVE_AMD_COMGR}
EOF

# --- glslangValidator ---
HAVE_GLSLANG_VALIDATOR=0
if command -v glslangValidator >/dev/null 2>&1; then
    HAVE_GLSLANG_VALIDATOR=1
fi
echo "  glslangValidator: $([ ${HAVE_GLSLANG_VALIDATOR} -eq 1 ] && echo yes || echo no)"
cat >> "${CONFIG_MK}" << EOF
HAVE_GLSLANG_VALIDATOR := ${HAVE_GLSLANG_VALIDATOR}
EOF

echo ""
echo "configure: wrote ${CONFIG_MK}"
