resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .githooks
    - .github
    - .gitlab
    - Dockerfiles
    - Docs
    - Scripts
    - '.*.y*ml'
    - '*.md'
    - '*.sln'

pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - .githooks
    - .github
    - .gitlab
    - Dockerfiles
    - Docs
    - Scripts
    - '.*.y*ml'
    - '*.md'
    - '*.sln'
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocm-examples.yml@pipelines_repo
