# MIT License
#
# Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Dependency checker for rocm-examples Makefile build system
#
# Usage in example Makefiles:
#   REQUIRED_DEPS := FFMPEG OPENCV
#   include $(COMMON_INCLUDE_DIR)/require_deps.mk
#
# Before including, set COMMON_INCLUDE_DIR (already standard in all examples).
#
# This file works in two modes:
#   1. Fast path: includes config.mk (generated by configure.sh) from the repo root
#   2. Fallback: uses inline pkg-config checks for standalone builds
#
# After including, check SKIP_BUILD. This composes with filter_hip_architectures.mk
# which also sets SKIP_BUILD.
#
# Output variables:
#   SKIP_BUILD   - set to 1 if any required dependency is missing
#   MISSING_DEPS - list of missing dependency names

# Locate the repository root relative to COMMON_INCLUDE_DIR
_REPO_ROOT := $(dir $(COMMON_INCLUDE_DIR))

# Try to include the pre-generated config.mk (silent if absent)
-include $(_REPO_ROOT)/config.mk

# If config.mk was not found, run inline fallback detection.
# We detect this by checking if HAVE_FFMPEG is defined (it's always written by configure.sh).
ifndef HAVE_FFMPEG
  # Fallback: detect dependencies via pkg-config / file existence

  # FFmpeg (pkg-config + link test to catch missing -dev packages)
  _FFMPEG_CHECK := $(shell pkg-config --exists libavcodec libavformat libavutil 2>/dev/null \
    && echo 'int main(){return 0;}' | $${CC:-cc} -x c - $$(pkg-config --libs libavcodec libavformat libavutil) -o /dev/null 2>/dev/null \
    && echo 1 || echo 0)
  HAVE_FFMPEG := $(_FFMPEG_CHECK)
  ifeq ($(HAVE_FFMPEG),1)
    FFMPEG_CFLAGS := $(shell pkg-config --cflags libavcodec libavformat libavutil 2>/dev/null)
    FFMPEG_LIBS := $(shell pkg-config --libs libavcodec libavformat libavutil 2>/dev/null || echo "-lavcodec -lavformat -lavutil")
  else
    FFMPEG_CFLAGS :=
    FFMPEG_LIBS :=
  endif

  # OpenCV (pkg-config + link test)
  _OPENCV_CHECK := $(shell (pkg-config --exists opencv4 2>/dev/null && echo 'int main(){return 0;}' | $${CC:-cc} -x c - $$(pkg-config --libs opencv4) -o /dev/null 2>/dev/null && echo 1) \
    || (pkg-config --exists opencv 2>/dev/null && echo 'int main(){return 0;}' | $${CC:-cc} -x c - $$(pkg-config --libs opencv) -o /dev/null 2>/dev/null && echo 1) \
    || echo 0)
  HAVE_OPENCV := $(_OPENCV_CHECK)
  ifeq ($(HAVE_OPENCV),1)
    OPENCV_CFLAGS := $(shell pkg-config --cflags opencv4 2>/dev/null || pkg-config --cflags opencv)
    OPENCV_LIBS := $(shell pkg-config --libs opencv4 2>/dev/null || pkg-config --libs opencv)
  else
    OPENCV_CFLAGS :=
    OPENCV_LIBS :=
  endif

  # GLFW3 (pkg-config + link test)
  _GLFW3_CHECK := $(shell pkg-config --exists glfw3 2>/dev/null \
    && echo 'int main(){return 0;}' | $${CC:-cc} -x c - $$(pkg-config --libs glfw3) -o /dev/null 2>/dev/null \
    && echo 1 || echo 0)
  HAVE_GLFW3 := $(_GLFW3_CHECK)
  ifeq ($(HAVE_GLFW3),1)
    GLFW3_CFLAGS := $(shell pkg-config --cflags glfw3 2>/dev/null)
    GLFW3_LIBS := $(shell pkg-config --libs glfw3 2>/dev/null)
  else
    GLFW3_CFLAGS :=
    GLFW3_LIBS :=
  endif

  # Vulkan (pkg-config + link test)
  _VULKAN_CHECK := $(shell pkg-config --exists vulkan 2>/dev/null \
    && echo 'int main(){return 0;}' | $${CC:-cc} -x c - $$(pkg-config --libs vulkan) -o /dev/null 2>/dev/null \
    && echo 1 || echo 0)
  HAVE_VULKAN := $(_VULKAN_CHECK)
  ifeq ($(HAVE_VULKAN),1)
    VULKAN_CFLAGS := $(shell pkg-config --cflags vulkan 2>/dev/null)
    VULKAN_LIBS := $(shell pkg-config --libs vulkan 2>/dev/null || echo "-lvulkan")
  else
    VULKAN_CFLAGS :=
    VULKAN_LIBS :=
  endif

  # libdw (elfutils)
  _LIBDW_CHECK := $(shell pkg-config --exists libdw 2>/dev/null && echo 1 || echo 0)
  ifeq ($(_LIBDW_CHECK),0)
    _LIBDW_CHECK := $(if $(or $(wildcard /usr/include/elfutils/libdw.h),$(wildcard /usr/include/dwarf.h)),1,0)
  endif
  HAVE_LIBDW := $(_LIBDW_CHECK)

  # amd_comgr
  ROCM_INSTALL_DIR ?= $(or $(ROCM_PATH),/opt/rocm)
  _AMD_COMGR_CHECK := $(if $(or $(wildcard $(ROCM_INSTALL_DIR)/include/amd_comgr/amd_comgr.h),$(wildcard $(ROCM_INSTALL_DIR)/lib/libamd_comgr.so)),1,0)
  ifeq ($(_AMD_COMGR_CHECK),0)
    _AMD_COMGR_CHECK := $(shell pkg-config --exists amd_comgr 2>/dev/null && echo 1 || echo 0)
  endif
  HAVE_AMD_COMGR := $(_AMD_COMGR_CHECK)

  # glslangValidator
  _GLSLANG_CHECK := $(shell command -v glslangValidator >/dev/null 2>&1 && echo 1 || echo 0)
  HAVE_GLSLANG_VALIDATOR := $(_GLSLANG_CHECK)

endif # ifndef HAVE_FFMPEG

# Check REQUIRED_DEPS against HAVE_<dep> flags
MISSING_DEPS :=
$(foreach dep,$(REQUIRED_DEPS),\
  $(if $(filter 1,$(HAVE_$(dep))),,\
    $(eval MISSING_DEPS += $(dep))))

ifneq ($(MISSING_DEPS),)
  SKIP_BUILD := 1
  $(info $(EXAMPLE): Skipping build — missing dependencies: $(MISSING_DEPS))
endif
