name: Build Libraries CUDA

on:
  workflow_dispatch:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'Libraries/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'Libraries/**'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    name: "Build Libraries CUDA"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rocm/rocm-examples-hip-libraries-cuda-ubuntu
      options: --user root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build hipCUB example
        shell: bash
        run: |
          cd Libraries/hipCUB
          make GPU_RUNTIME=CUDA -j

      - name: Build hipFFT example
        shell: bash
        run: |
          cd Libraries/hipFFT
          make GPU_RUNTIME=CUDA -j

      - name: Build hipSPARSELt examples
        shell: bash
        run: |
          cd Libraries/hipSPARSELt
          make GPU_RUNTIME=CUDA -j

      - name: Build rocRAND example
        shell: bash
        run: |
          cd Libraries/rocRAND
          make GPU_RUNTIME=CUDA -j
