name: Build HIP-Basic

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Basic/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Basic/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive
    GPU_TARGETS: gfx908;gfx90a;gfx942;gfx950;gfx1030;gfx1100;gfx1101;gfx1200;gfx1201

jobs:
    build:
        name: "Build HIP Examples"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/rocm/rocm-examples-ubuntu-24.04-rocm:7.14
        defaults:
            run:
                shell: bash
        steps:
          - uses: actions/checkout@v4
          - name: Generate skip lists
            run: |
              python3 .github/build_tools/generate_skip_tests.py --channel stable --target "${GPU_TARGETS%%;*}"
          - name: CMake Configure and Build
            run: |
              cd HIP-Basic
              cmake -DCMAKE_HIP_ARCHITECTURES="${GPU_TARGETS}" -DCMAKE_PROJECT_INCLUDE_BEFORE="${GITHUB_WORKSPACE}/Common/SkipExamples.cmake" -S . -B build
              cmake --build build -j
          - name: Make
            run: |
              cd HIP-Basic
              make -j SKIP_FROM_BUILD="$SKIP_FROM_BUILD"
