name: Build HIP-Doc CUDA

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Doc/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Doc/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive
    ROCM_VERSION: '7.2.4'
    AMDGPU_INSTALLER_VERSION: 7.2.4.70204-1

jobs:
    build:
        name: "Build HIP Documentation CUDA"
        runs-on: ubuntu-latest
        container:
            image: nvidia/cuda:12.9.2-cudnn-devel-ubuntu22.04
        defaults:
            run:
                shell: bash
        steps:
          - uses: actions/checkout@v4

          - name: Install dependencies
            run: |
                  apt-get update -qq &&
                  apt-get install -y build-essential g++ glslang-tools \
                    python3 python3-pip locales wget git libtiff-dev
                  python3 -m pip install --upgrade pip
                  python3 -m pip install cmake

          - name: Install Hip for CUDA
            run: |
              wget https://repo.radeon.com/amdgpu-install/${{ env.ROCM_VERSION }}/ubuntu/jammy/amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb
              apt-get -y install ./amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb &&
              apt-get update -qq &&
              apt-get install -y hip-dev hipify-clang hipfft-dev hipcub-dev

          - name: Configure, Build, and Install
            # The CMAKE_POLICY_VERSION_MINIMUM environment variable can be removed once the CMake updates from ROCm 7.0 are available
            run: |
              cd HIP-Doc
              export CMAKE_POLICY_VERSION_MINIMUM="3.5"
              cmake -DROCM_EXAMPLES_GPU_LANGUAGE=CUDA -DHIP_PLATFORM=nvidia -S . -B build
              cmake --build build -j
              cmake --install build --prefix install
