name: Build HIP-Basic

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Basic/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Basic/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive
    ROCM_VERSION: '7.2'
    AMDGPU_INSTALLER_VERSION: 7.2.70200-1
    GPU_TARGETS: gfx908;gfx90a;gfx942;gfx950;gfx1030;gfx1100;gfx1101;gfx1200;gfx1201

jobs:
    build:
        name: "Build HIP Examples"
        runs-on: ubuntu-latest
        container:
            image: ubuntu:22.04
        defaults:
            run:
                shell: bash
        steps:
          - uses: actions/checkout@v4
          - name: Install dependencies
            run: |
                  apt-get update -qq &&
                  apt-get install -y build-essential g++ glslang-tools \
                    python3 python3-pip libglfw3-dev libvulkan-dev locales wget pkg-config
                  python3 -m pip install --upgrade pip
                  python3 -m pip install cmake
          - name: Install ROCm Dev
            run: |
                  wget https://repo.radeon.com/amdgpu-install/${{ env.ROCM_VERSION }}/ubuntu/jammy/amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb
                  apt-get -y install ./amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb &&
                  apt-get update -qq &&
                  apt-get -y install rocm-dev rocm-llvm-dev
                  echo "/opt/rocm/bin" >> $GITHUB_PATH
                  echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
                  echo "LD_LIBRARY_PATH=/opt/rocm/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
                  apt-get autoclean
          - name: CMake Configure and Build
            run: |
              cd HIP-Basic
              cmake -DGPU_TARGETS="${GPU_TARGETS}" -S . -B build
              cmake --build build -j
          - name: Make
            run: |
              cd HIP-Basic
              make -j
