name: Build HIP-Doc

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Doc/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'HIP-Doc/**'
      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

env:
    DEBIAN_FRONTEND: noninteractive
    GPU_TARGETS: gfx908;gfx90a;gfx942;gfx950;gfx1030;gfx1100;gfx1101;gfx1200;gfx1201

jobs:
    build:
        name: "Build HIP Documentation"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/rocm/rocm-examples-ubuntu-24.04-rocm:7.14
        defaults:
            run:
                shell: bash
        steps:
          - uses: actions/checkout@v4
          - name: CMake Configure and Build
            # The CMAKE_POLICY_VERSION_MINIMUM environment variable can be removed once the CMake updates from ROCm 7.0 are available
            run: |
              cd HIP-Doc
              export CMAKE_POLICY_VERSION_MINIMUM="3.5"
              cmake -DGPU_TARGETS="${GPU_TARGETS}" -S . -B build
              cmake --build build -j
          - name: Make
            run: |
              cd HIP-Doc
              export HSA_XNACK=1
              make -j
