name: Build ROCm tool examples

on:
  push:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'Tools/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ amd-staging, amd-mainline, release/** ]
    paths:
      - 'Tools/**'
      - '.github/workflows/**'

env:
    ROCM_VERSION: '7.1'
    AMDGPU_INSTALLER_VERSION: 7.1.70100-1
    GPU_TARGETS: gfx803;gfx900;gfx906;gfx908;gfx90a;gfx942;gfx1030;gfx1100;gfx1101;gfx1102;gfx1201

jobs:
    build:
        name: "Build ROCm tool examples"
        runs-on: ubuntu-latest
        container:
            image: ubuntu:22.04
        steps:
          - uses: actions/checkout@v4
          - name: Install Python
            run: apt update -qq && apt install -y lsb_release python3 python3-pip python3-venv
          - uses: actions/setup-python@v6
            with:
              python-version: '>=3.3'
              cache: 'pip'
          - name: Install dependencies
            run: |
                  apt-get update -qq &&
                  apt-get install -y build-essential elfutils g++ git glslang-tools wget \
                    libboost-dev libiberty-dev libpapi-dev libopenmpi-dev libsqlite3-dev libtbb-dev libunwind-dev
                  python3 -m pip install --upgrade pip
                  python3 -m pip install cmake
          - name: Install ROCm Dev
            run: |
                  export DEBIAN_FRONTEND=noninteractive
                  wget https://repo.radeon.com/amdgpu-install/${{ env.ROCM_VERSION }}/ubuntu/jammy/amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb
                  apt-get -y install ./amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb &&
                  apt-get update -qq &&
                  apt-get -y install rocm-dev rocm-llvm-dev rocprofiler-compute rocprofiler-sdk rocprofiler-systems rocm-gdb
                  echo "/opt/rocm/bin" >> $GITHUB_PATH
                  echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
                  echo "LD_LIBRARY_PATH=/opt/rocm/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
                  apt-get autoclean
          - name: Set up Python
            run: pip install -r /opt/rocm/libexec/rocprofiler-compute/requirements.txt
          - name: Configure and Build
            shell: bash
            run: |
              cd Tools && mkdir build && cd build
              cmake -DGPU_TARGETS="${GPU_TARGETS}" -S ..
              cmake --build . -j 4
